"""Alembic environment.

Runs SYNCHRONOUSLY using psycopg2 (DATABASE_URL_SYNC). The application uses
asyncpg at runtime, but Alembic is a CLI tool with its own connection \u2014 no
reason to drag the asyncio event loop into migrations.

Migrations are HAND-WRITTEN, not autogenerated. Don't run
`alembic revision --autogenerate`; run `alembic revision -m "..."` and edit
the resulting file in migrations/versions/.
"""
from __future__ import annotations

import os
from logging.config import fileConfig

from alembic import context
from dotenv import load_dotenv
from sqlalchemy import engine_from_config, pool

# Load .env so DATABASE_URL_SYNC is available when Alembic CLI runs.
load_dotenv()

# Import metadata AFTER load_dotenv so models can read env if they need to.
from core.models import Base  # noqa: E402

target_metadata = Base.metadata

config = context.config
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

_db_url = os.environ.get("DATABASE_URL_SYNC")
if not _db_url:
    # Fall back to deriving the sync URL from the async one. This is the
    # common case for Neon / Supabase / Railway users who only set
    # DATABASE_URL and forget to also set DATABASE_URL_SYNC.
    async_url = os.environ.get("DATABASE_URL")
    if not async_url:
        raise RuntimeError(
            "Neither DATABASE_URL_SYNC nor DATABASE_URL is set. "
            "Copy .env.example to .env and set at least DATABASE_URL."
        )
    _db_url = async_url
    # Normalise scheme + swap async driver for sync.
    if _db_url.startswith("postgres://"):
        _db_url = _db_url.replace("postgres://", "postgresql+psycopg2://", 1)
    elif _db_url.startswith("postgresql+asyncpg://"):
        _db_url = _db_url.replace("postgresql+asyncpg://", "postgresql+psycopg2://", 1)
    elif _db_url.startswith("postgresql://"):
        _db_url = _db_url.replace("postgresql://", "postgresql+psycopg2://", 1)
    # asyncpg uses ?ssl=require, psycopg2 wants ?sslmode=require. If the
    # user wrote the async-style param, translate it for psycopg2.
    _db_url = _db_url.replace("?ssl=require", "?sslmode=require")
    _db_url = _db_url.replace("&ssl=require", "&sslmode=require")

print(f"[alembic] using DB host: {_db_url.split('@', 1)[-1].split('/', 1)[0]}")
config.set_main_option("sqlalchemy.url", _db_url)


def run_migrations_offline() -> None:
    """Generate SQL without a live DB connection (for review or batch apply)."""
    context.configure(
        url=_db_url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Apply migrations against the live DB."""
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
